//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listado
    {
        public int Id_Lista { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Cantidad_lista { get; set; }
        public Nullable<int> Id_producto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
