//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Listado = new HashSet<Listado>();
        }
    
        public int Id_producto { get; set; }
        public string Nombre_producto { get; set; }
        public string Cantidad_producto { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Listado> Listado { get; set; }
    }
}
